### ISSUE TITLE
read_timeout cannot be set

### ISSUE THREAD

**Issue by Crack** [pintsized/lua-resty-redis-connector#18]
In connector.lua you have:
```lua
r:set_timeout(self, config.read_timeout)
```
which passes connector object instance as timeout. It should be changed to:
```lua
r:set_timeout(config.read_timeout)
```

**Comment by Crack** [comment]
Hello,

Any chance of getting bugfix merged and released to OPM? This bug breaks usage with LuaSocket.

**Comment by hamishforbes** [comment]
Unfortunately I can't push out releases to opm (see https://github.com/openresty/opm/issues/61)
@pintsized will have to do that

**Comment by pintsized** [comment]
Uploaded v0.07 to opm and luarocks
